Repository 9oormthon-univ/2024_BEOTKKOTTHON_TEAM_27_FE, pull requests merged in 2024-03, with the labels that each got.

#4 [초기세팅] 프로젝트 생성
  .eslintrc.cjs
  .gitignore
  README.md
  index.html
  package.json
  public/vite.svg
  src/App.css
  src/App.tsx
  src/assets/react.svg
  src/index.css
  src/main.tsx
  src/vite-env.d.ts
  tsconfig.json
  tsconfig.node.json
  vite.config.ts
  yarn.lock
Labels: init 🍽️

#6 [초기세팅] CI/CD 구축
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
Labels: init 🍽️

#8 [초기세팅] 폴더 구조 세팅 및 라우팅 설정
  index.html
  package.json
  src/App.css
  src/App.style.ts
  src/App.tsx
  src/apis/.keep
  src/assets/.keep
  src/assets/react.svg
  src/components/PostNew/.keep
  src/components/common/PostHeader.tsx
  src/context/.keep
  src/core/.keep
  src/hooks/.keep
  src/layouts/Layout.tsx
  src/layouts/PostHeaderLayout.tsx
  src/pages/Home/Home.tsx
  src/pages/PostNew/PostNew.tsx
  src/pages/PostResult/PostResult.tsx
  src/router/Router.tsx
  src/style/.keep
  src/types/.keep
  yarn.lock
Labels: init 🍽️

#9 [초기세팅] eslint & prettier 적용
  .eslintrc.cjs
  .prettierrc
  package.json
  src/components/Error/NotFound.tsx
  src/components/common/Header.tsx
  src/layouts/HeaderLayout.tsx
  src/layouts/Layout.tsx
  src/layouts/PostHeaderLayout.tsx
  src/router/Router.tsx
  yarn.lock
Labels: init 🍽️

#11 [초기세팅] Global style & mobile resize
  package.json
  src/App.style.ts
  src/App.tsx
  src/hooks/.keep
  src/hooks/useMobile.tsx
  src/layouts/HeaderLayout.tsx
  src/layouts/Layout.tsx
  src/main.tsx
  src/style/.keep
  src/style/GlobalStyle.ts
  src/style/index.tsx
  src/style/theme.ts
  yarn.lock
Labels: init 🍽️

#13 [초기세팅] msw 세팅, tanstack-query 세팅 및 로딩 화면 세팅
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/.keep
  src/apis/client.ts
  src/apis/queryClients.ts
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/FallbackUI/FallbackUI.tsx
  src/pages/Home/Home.tsx
  src/pages/Loading/Loading.tsx
  yarn.lock
Labels: init 🍽️

#15 [공통] develop -> main 머지용 PR
  .eslintrc.cjs
  .prettierrc
  index.html
  package.json
  public/mockServiceWorker.js
  src/App.tsx
  src/apis/client.ts
  src/apis/queryClients.ts
  src/assets/.keep
  src/components/Error/NotFound.tsx
  src/components/PostNew/.keep
  src/components/common/Header.tsx
  src/context/.keep
  src/core/.keep
  src/hooks/useMobile.tsx
  src/layouts/HeaderLayout.tsx
  src/layouts/Layout.tsx
  src/main.tsx
  src/mocks/browser.ts
  src/mocks/handlers.ts
  src/pages/FallbackUI/FallbackUI.tsx
  src/pages/Home/Home.tsx
  src/pages/Loading/Loading.tsx
  src/pages/PostNew/PostNew.tsx
  src/pages/PostResult/PostResult.tsx
  src/router/Router.tsx
  src/style/GlobalStyle.ts
  src/style/index.tsx
  src/style/theme.ts
  src/types/.keep
  yarn.lock
Labels: merge 🎯

#23 [공유] 포스트 공유 화면 퍼블 및 기능 구현
  package.json
  src/App.tsx
  src/components/PostResult/PostButton.tsx
  src/components/PostResult/PostImage.tsx
  src/components/PostResult/PostText.tsx
  src/components/PostResult/PostTitle.tsx
  src/components/common/Button/ButtonWithTip/ButtonWithTip.tsx
  src/components/common/Button/ButtonWithTip/Tooltip.tsx
  src/components/common/Toggle/Toggle.tsx
  src/hooks/useWindowSize.tsx
  src/index.css
  src/layouts/HeaderLayout.tsx
  src/layouts/Layout.tsx
  src/mocks/handlers.ts
  src/pages/PostResult/PostResult.tsx
  src/router/Router.tsx
  src/style/theme.ts
  src/utils/android.ts
  src/utils/utils.ts
  yarn.lock
Labels: feat💡, style 🎨, 포스트공유📣

#29 [로그인] 로그인 및 가게 등록 퍼블
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  public/svg/search.svg
  public/svg/store.svg
  src/assets/Image/sodong_smile.png
  src/assets/svg/Search.tsx
  src/assets/svg/Store.tsx
  src/assets/svg/index.ts
  src/components/Login/LoginInput.tsx
  src/components/Login/LoginTop.tsx
  src/components/StoreNew/StoreResult.tsx
  src/components/StoreNew/StoreResultNone.tsx
  src/components/StoreNew/StoreSearch.tsx
  src/components/common/Button/ButtonFill/ButtonFill.tsx
  src/layouts/StoreHeaderLayout.tsx
  src/main.tsx
  src/mocks/handlers.ts
  src/pages/Login/Login.tsx
  src/pages/MyStoreAdd/MyStoreAdd.tsx
  src/pages/PostResult/PostResult.tsx
  src/pages/StoreNew/StoreNew.tsx
  src/router/Router.tsx
  src/style/theme.ts
  src/types/PostNew/index.d.ts
  src/types/StoreNew/index.d.ts
Labels: feat💡, style 🎨, 로그인 💫

#28 [포스트생성] 생성 퍼넬 패턴 구현
  src/assets/Image/Instagram.png
  src/assets/Image/PostImg.png
  src/assets/Image/food1.jpg
  src/assets/Image/food2.jpg
  src/assets/Image/food3.jpg
  src/components/Home/HomeSubsection/HomeSubsection.tsx
  src/components/PostHistory/TextCardWithImage/TextCardWithImage.tsx
  src/components/PostNew/PostFooter/PostFooter.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/PostNew/Step1/Step1Title/Step1Title.tsx
  src/components/PostNew/Step2/Step2.tsx
  src/components/PostNew/Step3/Step3.tsx
  src/components/PostNew/Step4/Step4.tsx
  src/components/PostNew/Step5/Step5.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/components/common/Funnel/Funnel.tsx
  src/components/common/ProcessBar/ProcessBar.tsx
  src/context/PostNew/PonstNewContext.tsx
  src/core/PostNew/Onboarding.ts
  src/hooks/PostNew/useSnsSelect.tsx
  src/hooks/useFunnel.tsx
  src/pages/PostHistory/PostHistoryPage.tsx
  src/pages/PostNew/PostNew.tsx
  src/router/Router.tsx
  src/types/.keep
  src/types/PostNew/index.d.ts
  src/types/utility.ts
  src/utils/error.ts
Labels: feat💡, style 🎨, 포스트생성 🎫, 포스팅히스토리 🖥️

#34 [포스트생성] 포스팅 상태 아카이빙 및 이미지 업로드 통신
  src/apis/client.ts
  src/components/PostNew/PostFooter/PostFooter.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/PostNew/Step2/SelectAge/SelectAge.tsx
  src/components/PostNew/Step2/SelectGender/SelectGender.tsx
  src/components/PostNew/Step2/Step2.tsx
  src/components/PostNew/Step3/SelectType/SelectType.tsx
  src/components/PostNew/Step3/Step3.tsx
  src/components/PostNew/Step4/Step4.tsx
  src/components/PostNew/Step5/Step5.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/context/PostNew/PonstNewContext.tsx
  src/context/PostNew/PostNewContext.tsx
  src/hooks/PostNew/useMenuExplain.tsx
  src/hooks/PostNew/useMenuInput.tsx
  src/hooks/PostNew/useSnsSelect.tsx
  src/pages/PostNew/PostNew.tsx
  src/queries/PostNew/usePostInfo.tsx
  src/queries/PostNew/useUploadImage.tsx
  src/queries/PostResult/.keep
  src/router/Router.tsx
  src/types/PostNew/index.d.ts
Labels: feat💡, API 🧬, 포스트생성 🎫

#33 [로그인] 로그인, 가게 등록 API 연결
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  src/components/StoreNew/StoreResult.tsx
  src/hooks/mutations/store/usePostStore.ts
  src/hooks/mutations/user/usePostLogin.ts
  src/hooks/queries/kakao/useGetKakaoSearch.ts
  src/pages/Login/Login.tsx
  src/pages/StoreNew/StoreNew.tsx
  src/types/Response/index.d.ts
  src/types/StoreNew/index.d.ts
Labels: API 🧬, 로그인 💫

#37 [포스트공유] API 연결
  package.json
  public/svg/image.svg
  public/svg/text.svg
  src/apis/client.ts
  src/apis/fastClient.ts
  src/assets/svg/Image.tsx
  src/assets/svg/Text.tsx
  src/assets/svg/index.ts
  src/components/PostNew/Step6/Step6.tsx
  src/components/PostResult/PostBottomSheet.tsx
  src/components/PostResult/PostTitle.tsx
  src/components/common/Loading/Loading.tsx
  src/hooks/mutations/post/usePutPost.ts
  src/hooks/queries/post/useGetPost.ts
  src/pages/PostResult/PostResult.tsx
  src/router/Router.tsx
  src/style/theme.ts
  src/types/Post/index.d.ts
  src/utils/utils.ts
  yarn.lock
Labels: API 🧬, 포스트공유📣

#38 [이용가이드] 이용가이드
  src/assets/Image/guide_create.webp
  src/assets/Image/guide_use.webp
  src/components/Home/HomeSubsection/HomeSubsection.tsx
  src/pages/Guide/GuidePage.tsx
  src/router/Router.tsx
  src/style/theme.ts
Labels: feat💡, style 🎨

#39 [포스트생성] 포스트 생성 - 결과 플로우
  .github/workflows/deploy.yml
  .github/workflows/preview.yml
  src/apis/fastClient.ts
  src/components/PostNew/Step3/SelectType/SelectType.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/main.tsx
  src/pages/PostNew/PostNew.tsx
  src/queries/PostNew/usePostInfo.tsx
Labels: feat💡, API 🧬, 포스트생성 🎫

#40 [포스트상세] 퍼블 마무리 및 API 연결
  public/svg/icArrow.svg
  src/assets/svg/IcArrow.tsx
  src/assets/svg/index.ts
  src/components/Post/PostBottomSheet.tsx
  src/components/Post/PostButton.tsx
  src/components/Post/PostImage.tsx
  src/components/Post/PostResultTitle.tsx
  src/components/Post/PostText.tsx
  src/components/Post/PostTop.tsx
  src/components/PostResult/PostImage.tsx
  src/components/PostResult/PostText.tsx
  src/components/common/Header.tsx
  src/layouts/HeaderLayout.tsx
  src/pages/Guide/GuidePage.tsx
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostHistory/PostHistoryPage.tsx
  src/pages/PostResult/PostResult.tsx
  src/pages/PostResult/PostResultPage.tsx
  src/pages/StoreNew/StoreNewPage.tsx
  src/router/Router.tsx
  src/style/theme.ts
  src/utils/utils.ts
Labels: API 🧬

#41 [포스팅 히스토리] 포스팅 히스토리 API 연결
  src/assets/Image/LoadingSodong.gif
  src/components/PostHistory/TextCardWithImage/TextCardWithImage.tsx
  src/components/PostNew/PostFooter/PostFooter.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/PostNew/Step2/SelectAge/SelectAge.tsx
  src/components/PostNew/Step2/Step2.tsx
  src/components/PostNew/Step3/SelectType/SelectType.tsx
  src/components/PostNew/Step3/Step3.tsx
  src/components/PostNew/Step4/Step4.tsx
  src/components/PostNew/Step5/Step5.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/components/common/Loading/Loading.tsx
  src/hooks/queries/post/useGetHistory.ts
  src/pages/PostHistory/PostHistoryPage.tsx
  src/pages/PostNew/PostNew.tsx
  src/queries/PostHistory/useGetHistory.tsx
Labels: feat💡, API 🧬, 포스팅히스토리 🖥️

#44 [포스트 공유] utils 함수 수정
  src/components/Post/PostButton.tsx
  src/core/.keep
  src/core/Post.ts
  src/utils/utils.ts
Labels: fix 🛠️

#46 [포스트생성] UI 개선 및 다음 버튼 수정
  src/components/PostHistory/TextCardWithImage.tsx
  src/components/PostNew/.keep
  src/components/PostNew/PostFooter/NextButton.tsx
  src/components/PostNew/PostHeader/PostNewHeader.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/PostNew/Step2/SelectAge/SelectAge.tsx
  src/components/PostNew/Step2/Step2.tsx
  src/components/PostNew/Step3/SelectType/SelectType.tsx
  src/components/PostNew/Step3/Step3.tsx
  src/components/PostNew/Step4/Step4.tsx
  src/components/PostNew/Step5/Step5.tsx
  src/components/PostNew/Step5/Tip/Tip.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/components/common/ProcessBar/ProcessBar.tsx
  src/components/common/Title/Title.tsx
  src/hooks/PostNew/useMenuExplain.tsx
  src/hooks/PostNew/useMenuInput.tsx
  src/pages/PostHistory/PostHistoryPage.tsx
  src/pages/PostNew/PostNewPage.tsx
  src/router/Router.tsx
  src/style/theme.ts
Labels: fix 🛠️, 포스트생성 🎫

#47 [포스트 공유] 포스트 완료 UI 변경 반영
  public/svg/icRetry.svg
  src/assets/svg/IcRetry.tsx
  src/assets/svg/index.ts
  src/components/Post/PostButton.tsx
  src/components/Post/PostImage.tsx
  src/components/Post/PostResultTitle.tsx
  src/components/Post/PostRetry.tsx
  src/components/PostHistory/TextCardWithImage.tsx
  src/components/common/Button/ButtonWithTip/ButtonWithTip.tsx
  src/components/common/Button/ButtonWithTip/Tooltip.tsx
  src/pages/Login/Login.tsx
  src/pages/PostNew/PostNewPage.tsx
  src/pages/PostResult/PostResultPage.tsx
  src/pages/StoreNew/StoreNewPage.tsx
  src/router/Router.tsx
  src/style/theme.ts
Labels: style 🎨

#51 [포스트 히스토리] UI 개선
  package.json
  src/assets/Image/kakao.png
  src/components/Post/PostButton.tsx
  src/components/Post/PostImage.tsx
  src/components/Post/PostText.tsx
  src/components/Post/PostTop.tsx
  src/components/PostHistory/TextCardWithImage.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/common/Loading/Progress.tsx
  src/core/Post.ts
  src/pages/PostDetail/PostDetailPage.tsx
  src/pages/PostHistory/PostHistoryPage.tsx
  src/pages/PostResult/PostResultPage.tsx
  yarn.lock
Labels: style 🎨

#50 [홈] 홈 화면 리디자인
  public/svg/ChatGptIc.svg
  public/svg/GuideIc.svg
  public/svg/HistoryIc.svg
  public/svg/KoGptIc.svg
  public/svg/MyStoreIc.svg
  public/svg/PostNewIc.svg
  public/svg/footer.svg
  public/svg/profileImg.svg
  src/assets/Icon/eventIc.png
  src/assets/Icon/femalIc.png
  src/assets/Icon/maleIc.png
  src/assets/Icon/menuIc.png
  src/assets/svg/ChatGptIc.tsx
  src/assets/svg/Footer.tsx
  src/assets/svg/GuideIc.tsx
  src/assets/svg/HistoryIc.tsx
  src/assets/svg/KoGptIc.tsx
  src/assets/svg/MyStoreIc.tsx
  src/assets/svg/PostNewIc.tsx
  src/assets/svg/ProfileImg.tsx
  src/assets/svg/index.ts
  src/components/Home/HomeSubsection/HomeSubsection.tsx
  src/components/PostNew/PostHeader/PostNewHeader.tsx
  src/components/PostNew/Step1/Step1.tsx
  src/components/PostNew/Step1/Step1Title/Step1Title.tsx
  src/components/PostNew/Step2/PostTitle/PostTitle.tsx
  src/components/PostNew/Step2/SelectGender/SelectGender.tsx
  src/components/PostNew/Step2/Step2.tsx
  src/components/PostNew/Step3/SelectType/SelectType.tsx
  src/components/PostNew/Step3/Step3.tsx
  src/components/PostNew/Step4/Step4.tsx
  src/components/PostNew/Step5/Step5.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/pages/Home/HomePage.tsx
  src/pages/PostNew/PostNewPage.tsx
  src/style/theme.ts
Labels: refactor ⚙️, style 🎨

#55 [QA 1차] CSS 요청사항 반영
  public/vite.svg
  src/assets/Image/guide_create.webp
  src/assets/Image/guide_use.webp
  src/components/Login/LoginInput.tsx
  src/components/common/Loading/Loading.tsx
  src/components/common/Loading/Progress.tsx
  src/pages/Guide/GuidePage.tsx
  src/pages/Login/Login.tsx
  src/pages/StoreNew/StoreNewPage.tsx
Labels: fix 🛠️

#56 [HOTFIX] step 6 다음 버튼 크기 조정
  src/components/PostNew/PostFooter/NextButton.tsx
  src/components/PostNew/Step6/Step6.tsx
  src/components/common/Button/ButtonFill/ButtonFill.tsx
Labels: refactor ⚙️, 포스트생성 🎫

#58 [리드미] 리드미.md 업데이트
  README.md
Labels: merge 🎯
